// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuajiiusihcfoenzkohf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1YWppaXVzaWhjZm9lbnprb2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTE2OTUsImV4cCI6MjA2MTc2NzY5NX0.F2X1TvI8AMwcw-yuy4RgWCv_y2b3QkMt9FTluF1fX7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);